import 'package:demo_work/model/movie_model.dart';
import 'package:get/state_manager.dart';
import 'package:get/get_state_manager/src/simple/get_controllers.dart';

class MovieController extends GetxController {

  var isLoading = true.obs;
  var movieList = List<MovieModel>().obs;
  var selectedIndex = 0.obs;


  @override
  void onInit() {
    fetchMovies();
  }

  void fetchMovies() async{
    try{
      isLoading(true);
      movieList.add(MovieModel(movieName: "The Hillfsdfsdfsdfdsf dsdf ds",image: "assets/images/movie1.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms.\n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms\n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms\n "));
      movieList.add(MovieModel(movieName: "The Legend",image: "assets/images/movie2.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' \n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms \n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms\n tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "Freedom",image: "assets/images/movie3.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms. \n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms\n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms\n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms \n a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-armsa manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms"));
      movieList.add(MovieModel(movieName: "Best Picture",image: "assets/images/movie4.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "Based on the Depression-era bildungsroman memoir of writer A. E. Hotchner, the film follows the story of a boy struggling to survive on his own in a hotel in St. Louis after his mother is committed to a sanatorium with tuberculosis. His father, a German immigrant and traveling salesman working for the Hamilton Watch Company, is off on long trips from which the boy cannot be certain he will return. \n Based on the Depression-era bildungsroman memoir of writer A. E. Hotchner, the film follows the story of a boy struggling to survive on his own in a hotel in St. Louis after his mother is committed to a sanatorium with tuberculosis. His father, a German immigrant and traveling salesman working for the Hamilton Watch Company, is off on long trips from which the boy cannot be certain he will return. \nBased on the Depression-era bildungsroman memoir of writer A. E. Hotchner, the film follows the story of a boy struggling to survive on his own in a hotel in St. Louis after his mother is committed to a sanatorium with tuberculosis. His father, a German immigrant and traveling salesman working for the Hamilton Watch Company, is off on long trips from which the boy cannot be certain he will return."));
      movieList.add(MovieModel(movieName: "After",image: "assets/images/movie5.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "Black Widow",image: "assets/images/movie6.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "Joker",image: "assets/images/movie7.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "Beauty and the best",image: "assets/images/movie8.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "Produgal",image: "assets/images/movie9.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "June",image: "assets/images/movie10.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.add(MovieModel(movieName: "F9",image: "assets/images/movie11.jpg",writer: "kjfskjdf  das",relasedate: "12-01-12",description: "North Africa, World War II. British soldiers on the brink of collapse push beyond endurance to struggle up a brutal incline. It's not a military objective. It's The Hill, a manmade instrument of torture, a tower of sand seared by a white-hot sun. And the troops' tormentors are not the enemy, but their own comrades-at-arms."));
      movieList.obs;
    }
    finally{
      isLoading(false);
    }
  }

  void setSelectedIndex(int i) {
    selectedIndex.value = i;
  }

  dynamic getSelectedIndex(){
    return selectedIndex;
  }

  void getMovieDetails(int index) {
    var moviedetails = movieList[index];
    print("moviedetails : $moviedetails");
  }
}